### ISSUE TITLE
Cloudpanel v2 backup folder incorrect

### ISSUE THREAD

**Issue by semaf** [foxly-it/Backup-CloudPanel-Nextcloud#2]
Hey,

Thanks for the great script. Just want to inform you that Cloudpanel create new directories for each website in /home/.
If you have created a new site with the name "wordpress" than you have "/home/wordpress/". 

There is also "/home/wordpress/backups" where database backups are stored.

**Comment by foxly-it** [comment]
Hi, thanks for the information. I haven't uploaded the new script to github yet. Sorry, but I will take care of it.

**Comment by semaf** [comment]
Thank you!

**Comment by foxly-it** [comment]
> Thank you!

The new version is now available.
